use common::events::ServerEffect;
use common::events::ServerEvent;

use crate::error::ClientResult;

// State types: serialized to JS, diffable. Add `#[derive(Default)]` etc. as needed.
//
// Hand-written `macro_rules!` (rather than `macro_rules_attribute::attribute_alias!`)
// so that rust-analyzer can resolve and expand `#[apply(client_state)]`. RA fails to
// resolve the macros generated by `attribute_alias!`, which makes every annotated type
// opaque to the IDE (no hover/completion/go-to-def).
macro_rules! client_state {
    ($($item:tt)*) => {
        #[derive(serde::Serialize, serde::Deserialize, Clone, diff::Diff, Debug)]
        #[cfg_attr(feature = "wasm", derive(tsify_next::Tsify))]
        #[cfg_attr(feature = "wasm", tsify(into_wasm_abi))]
        #[diff(attr(
            #[derive(serde::Serialize, Clone, Debug)]
        ))]
        $($item)*
    };
}

// Event types: deserialized from JS, not diffable.
macro_rules! client_event {
    ($($item:tt)*) => {
        #[derive(serde::Deserialize, Clone, Debug)]
        #[cfg_attr(feature = "wasm", derive(tsify_next::Tsify))]
        #[cfg_attr(feature = "wasm", tsify(from_wasm_abi))]
        $($item)*
    };
}

pub mod error;
pub mod reducers;
pub mod state;

pub trait ServerEventDispatcher {
    fn dispatch(
        &self,
        event: &ServerEvent,
    ) -> impl futures::Future<Output = ClientResult<Vec<ServerEffect>>>;
}

#[cfg(feature = "wasm")]
pub mod wasm;
